type: "paired" # single or paired

genome_sequence: "/path/to/mm10/genome.fa" # path to fasta of genome

genome_index_loc: "/path/to/isoseq/gmap" # path to basename of gmap index

genome_index_name: "mm10"

tmpdir: ""

sample_list: "/path/to/snake_iso/sample_list2.txt" ## text file of sample names

fastq_dir: "/path/to/data" ## location of fasta files

out_dir: "/path/to/snake_iso" ## directory to hold results

cluster_report: "/path/to/data/IsoSeq.polished.cluster_report.csv"

merge_samples: "TRUE" ##if multiple samples are present, should they be merged prior to aligning

threads_for_alignment: 20

gtf: "/path/to/hisat_genome/UCSC_mm10_compGENCODE22.gtf" # path to reference annotation gtf file
